### ISSUE TITLE
Extra `$DisplayFunction` block when plotting a user defined function

### ISSUE THREAD

**Issue by lyyc199586** [njpipeorgan/wolfram-language-notebook#14]
**Describe the bug**
When plotting a defined function, there is an extra `$DisplayFunction[]` around the desired figure.

**Expected behavior**
Directly output the figure

**Screenshots**
![image](https://user-images.githubusercontent.com/20653957/150662641-3246204a-8f2a-4474-b907-fa9b7f273b63.png)

**Environment (please complete the following information):**
 - Operating system: Windows 11
 - Mathematica/Engine: 13.0
 - VS Code: 1.63
 - Version: 0.0.8

**Comment by njpipeorgan** [comment]
Thanks for the feedback.

I suspect that this problem is also related to the WSL environment. `$DisplayFunction` is normally `Identity`, but it may be undefined in your case (you can check this by directly evaluating `$DisplayFunction`). If that is true, `$DisplayFunction=Identity;` can be a solution for you. [A related question](https://mathematica.stackexchange.com/questions/5682/what-does-displayfunction-identity-do-to-graphics-functions)

**Comment by lyyc199586** [comment]
No I am using it directly from windows now, not WSL

**Comment by njpipeorgan** [comment]
I see. When this problem occurs, what is the value of $DisplayFunction?

**Comment by lyyc199586** [comment]
add `DisplayFunction->Identity` can solve this problem
